title:computing in context - Yansong Ran
author: Yansong Ran
only build toc files: true
execute:
execute notebooks: "off"

sphinx:
config:
# https://myst-parser.readthedocs.io/en/latest/syntax/cross-referencing.html#implicit-targets
myst heading anchors: 4# https://jupyterbook.org/en/stable/interactive/interactive.html#plotly
html is files:
-https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
suppress warnings:["mystnb.unknown mime type"]
