name: computing-in-context
channels:
  - default
  - conda-forge
dependencies:
  - jupyter-book=1.*
  # https://github.com/sphinx-doc/sphinx/issues/10440#issuecomment-1556180835
  - pandas
  # https://plotly.com/python/mapbox-to-maplibre/
  - plotly>=5.24.0
  - sphinx>=6.2.0
  - statsmodels
  # https://pandas.pydata.org/docs/user_guide/io.html#excel-files
  - xlrd
